### ISSUE TITLE
Returning true/false based on an `if`

### ISSUE THREAD

**Issue by edbennett** [LupoA/lsdensities#34]
This is a pedantic issue, but there is usually not a reason to write something like

```python
if some_condition_that_is_boolean:
    return True
else:
    return False
```

The reason: `some_condition_that_is_boolean` is already `True` or `False`, so you can return it directly:

```python
return some_condition_that_is_boolean
```

Bam, your function is 3 lines shorter so there are 3 fewer lines of code to need to understand.

**Comment by edbennett** [comment]
Note that adding `"SIM"` to the `ruff` linting options will point this out to avoid reintroducing it.

**Comment by nickforce989** [comment]
This have been solved by ruff.

**Comment by edbennett** [comment]
It's still present in `src/lsdensities/InverseProblemWrapper.py`. Add `"SIM"` to line 35 of `pyproject.toml` and then run `pre-commit run --all` and it will highlight it.

**Comment by nickforce989** [comment]
Done.

**Comment by edbennett** [comment]
Fab; can you fix the other issues that `SIM` now highlights?

**Comment by nickforce989** [comment]
It appears that no issues are detected.

**Comment by edbennett** [comment]
Weird, I see two issues on my machine.

```
$ pre-commit run --all
ruff.....................................................................Failed
- hook id: ruff
- exit code: 1

src/lsdensities/InverseProblemWrapper.py:675:17: SIM102 Use a single `if` statement instead of nested `if` statements
src/lsdensities/utils/rhoUtils.py:237:13: SIM113 Use `enumerate()` for index variable `indx` in `for` loop
Found 2 errors.
No fixes available (1 hidden fix can be enabled with the `--unsafe-fixes` option).

ruff-format..............................................................Passed
check yaml...............................................................Passed
fix end of files.........................................................Passed
trim trailing whitespace.................................................Passed
check toml...............................................................Passed
mixed line ending........................................................Passed
```

**Comment by nickforce989** [comment]
Ok, now I get them too, and I solved it.
